In [ ]:
import pandas as pd

In [14]:
df = pd.read_csv(
    "/home/isaacp/research/repos/EvMatsim/scenarios/utahev/output/ITERS/it.0/0.chargingStats.csv",
    sep=";",
)

In [15]:
df.head(100)

,chargerId,vehicleId,linkId,waitStartTime,waitEndTime,waitDuration,chargeStartTime,chargeEndTime,chargingDuration,energyTransmitted_kWh
0,1,1,371,00:00:00,01:04:08,00:00:00,01:04:08,01:04:10,00:00:02,0.0
1,2,1,16224,00:00:00,01:04:10,00:00:00,01:04:10,01:04:25,00:00:15,0.0
2,3,1,372,00:00:00,01:04:25,00:00:00,01:04:25,01:04:28,00:00:03,0.0
3,4,1,90,00:00:00,01:04:28,00:00:00,01:04:28,01:04:32,00:00:04,0.0
4,5,1,20800,00:00:00,01:04:32,00:00:00,01:04:32,01:04:34,00:00:02,0.0
...,...,...,...,...,...,...,...,...,...,...
56,57,1,17405,00:00:00,01:05:53,00:00:00,01:05:53,01:05:57,00:00:04,0.0
57,58,1,20802,00:00:00,01:05:57,00:00:00,01:05:57,01:05:59,00:00:02,0.0
58,59,1,20767,00:00:00,01:05:59,00:00:00,01:05:59,01:06:03,00:00:04,0.0
59,60,1,17404,00:00:00,01:06:03,00:00:00,01:06:03,01:06:08,00:00:05,0.0
60,61,1,13484,00:00:00,01:06:08,00:00:00,01:06:08,01:06:11,00:00:03,0.0